service: point-record-serverless

provider:
  name: aws
  stage: api
  region: sa-east-1
  runtime: nodejs14.x
  memorySize: 128
  timeout: 30
  lambdaHashingVersion: 20201221

frameworkVersion: '2'

plugins:
  - serverless-pseudo-parameters
  - serverless-offline

custom:
  bundle:
    forceInclude:
      - pg
    ignorePackages:
      - pg-native

package:
  individually: false

functions:
  - ${file(handlers/point-record/point-record.yml)}
  - ${file(handlers/point-integration-log/point-integration-log.yml)}
  
